### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by kroese** [Rickebo/Lemmy.Net#1]
When you try to post an item with an invalid character in the title, the library returns an error like this:

```
Response status code does not indicate success: 400 (Bad Request).
 ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
```

Which is not very helpful in determining the reason why it failed.

It would be nice if the library instead would return the lemmy error message ("invalid_character in title") instead of the http error code.

**Comment by Rickebo** [comment]
This should be implemented in 7819c6005d0c5d46c65bbbd762abec14cfbbd3cb. If the API returns an unsuccessful status code like 400, an ApiException is thrown instead which has an Error property that contains the Lemmy error message.
