### ISSUE TITLE
Add thumbnail to post

### ISSUE THREAD

**Issue by kroese** [Rickebo/Lemmy.Net#2]
It would be very nice if you could add the thumbnail image to CreatePost().

I know the original JS library also does not support this, so if you want to exactly clone their calls I'll have to wait until they add support for it first.

**Comment by Rickebo** [comment]
Sorry for the late reply. I do not plan to exactly clone their calls, but simply based the initial version of my API wrapper on theirs by porting their code to C#. 

Regarding thumbnails, do you mean that it would be nice to include the image in CreatePost, and not just use the URL property to link to an already uploaded image? If so, it would be a convenient feature, and one that I could implement along with adding the UploadImage request (https://github.com/Rickebo/Lemmy.Net/issues/3) perhaps.
